[project]
name = "moe-geoportal-loader"
version = "1.6.4"
description = ""
authors = [
    {name = "Keita Uemori", email = "geo.jagaimo@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = [
    "pyqt5-stubs>=5.15.6.0",
    "ruff>=0.8.2",
]
