[project]
name = "moe-geoportal-loader"
version = "1.0.0"
description = "A QGIS plugin for adding data from the moe-geoportal."
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = [
    "pyqt5-stubs>=5.15.6.0",
    "ruff>=0.8.2",
]
