name: Test plugin

on:
  pull_request:
    branches:
      - main

env:
  # Docker settings
  DOCKER_IMAGE: qgis/qgis

jobs:
  Test-plugin:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        docker_tags: [release-3_34, latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker pull and create qgis-testing-environment
        run: |
          docker pull "$DOCKER_IMAGE":${{ matrix.docker_tags }}
          docker run -d --name qgis-testing-environment -v .:/tests_directory/plugin_dir -e DISPLAY=:99 "$DOCKER_IMAGE":${{ matrix.docker_tags }}

      - name: Docker set up QGIS
        run: |
          docker exec qgis-testing-environment sh -c "qgis_setup.sh plugin_dir"
          docker exec qgis-testing-environment sh -c "rm -f /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/plugin_dir"
          docker exec qgis-testing-environment sh -c "ln -s /tests_directory/plugin_dir /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/plugin_dir"

      - name: Start Xvfb
        run: |
          docker exec -d qgis-testing-environment sh -c "Xvfb :99 -screen 0 1024x768x24 -nolisten tcp &"
          sleep 3

      - name: Docker run plugin tests
        run: |
          docker exec qgis-testing-environment sh -c "qgis_testrunner.sh plugin_dir.test.test_suite.test_package"
